[{"name": "test.test_seven_brothers.SevenBrothersTest.test_content", "status": "failed", "message": "'Simeoni' != 'Aapo'\n- Simeoni\n+ Aapo\n : Line 1 in output is incorrect.", "passed": false, "points": ["1.seven_brothers"], "backtrace": ["  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"C:\\Users\\jlam\\Documents\\TMC MOOC\\IdeaProjects\\TMCProjects\\mooc-programming-22\\part01-02_seven_brothers\\test\\test_seven_brothers.py\", line 19, in test_content\n    self.assertEqual(split_output[i], correct[i], \"Line {0} in output is incorrect.\".format(i + 1))\n", "  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 1209, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n", "  File \"C:\\Users\\jlam\\AppData\\Local\\Programs\\Python\\Python39\\lib\\unittest\\case.py\", line 668, in fail\n    raise self.failureException(msg)\n"]}]